### PR TITLE
Externalized config, code cleanup, resource checking

### PR DESCRIPTION
**Pull request by peterschen**
Please merge my changes as they improve the usability of the script greatly. The configuration is now externalized and could be create automatically or be changed without endangering the functionality of the script.

Furthermore I added checks to verify that required resources (like Convert-WindowsImage.ps1) are actually present before dumping with an exception (the same goes for .iso/.wim files).

### CODE REVIEW

**Comment by BenjaminArmstrong** [comment]
Peter - while I agree with a number of the goals you have here, there are some aspects that I am not a fan of.  For one - I do not like having to deal with excessive amounts of XML (I avoid it if possible).  

Is there any reason that you use an XML file for external configuration as opposed to a .PS1 that you can dot source?

**Comment by peterschen** [comment]
Hey Ben,

Haven't really thought about it before. I had this code laying around so I re-used it. The advantage of XML in this case is that it can be validated and misconfiguration can be prevented. A dot-sourced .ps1 is much harder to validate and may break the proper execution of the factory.

BR
Chris

**Comment by peterschen** [comment]
I'll close this one and spread the changes over more pull requests so I can address other issues separately.

**Comment by BenjaminArmstrong** [comment]
Thanks!  There was some good stuff here - but breaking it up into small chunks will make it easier for me to validate and review.

**Pull request closed without merging**
